---
title: "Visualization"
author: "Sarah Mixon"
date: "4/9/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(readr)
library(data.table)

# Get data from github repo 
require(RCurl)
samesex_data <- read.csv(text=getURL("https://raw.githubusercontent.com/zonination/samesmarriage/master/ssm.csv"))

# each obs is one state in one year
ssm_tidy <- setNames(melt(samesex_data, id = c("State", "abbrev")), c("State", "abbrev", "Year", "Law"))

```

# DATA VISUALIZATION 
## The dataset is the legal status of same-sex marriage by each US state (50 observations) from 1995-2015. 

```{r visual 1}

# stacked bar chart 
ggplot(data = ssm_tidy) +
  geom_bar(mapping = aes(x = Year, fill = Law)) +
  coord_flip() +
  labs(title = "Legal Status of Same-Sex Marriage in the US (1995-2015)",
       x = "number of states",
       y = "year",
       caption = "(based on data from the Pew Research Center)")
ggsave("stacked_ssm.png")

# beside bar chart
ggplot(data = ssm_tidy) +
  geom_bar(mapping = aes(x = Year, fill = Law), position = "dodge") +
    labs(title = "Legal Status of Same-Sex Marriage in the US (1995-2015)",
       x = "number of states",
       y = "year",
       caption = "(based on data from the Pew Research Center)")
ggsave("dodge_ssm.png")

```

```{r visual 2}

# stacked bar chart with x = year 
ggplot(data = ssm_tidy) +
  geom_bar(mapping = aes(x = Year, fill = Law)) +
  labs(title = "Legal Status of Same-Sex Marriage in the US (1995-2015)",
       x = "year",
       y = "number of states",
       caption = "(based on data from the Pew Research Center)") +
  theme(axis.text.x = element_text(angle = -50))
ggsave("stacked_year_x.png")

```

```{r visual 3}

# facet wrap ~ law type 
ggplot(data = ssm_tidy) +
  geom_bar(mapping = aes(x = Year, fill = Law)) +
  facet_wrap(~Law, nrow = 2) +
    labs(title = "Legal Status of Same-Sex Marriage in the US (1995-2015)",
       x = "year",
       y = "number of states",
       caption = "(based on data from the Pew Research Center)") +
    theme(axis.text.x = element_text(angle = -85))
ggsave("facet_law.png")

# facet wrap ~ year
ggplot(data = ssm_tidy) +
  geom_bar(mapping = aes(x = Law, fill = Law)) +
  facet_wrap(~Year, nrow = 3) +
    labs(title = "Legal Status of Same-Sex Marriage in the US (1995-2015)",
       y = "number of states",
       caption = "(based on data from the Pew Research Center)") +
      theme(axis.title.x = element_blank(),
            axis.text.x = element_blank(),
            axis.ticks.x = element_blank())
ggsave("facet_year.png")
```


```{r visual four}

# ordering the levels of Law
ssm_tidy$Law <- factor(ssm_tidy$Law, levels = c("No Law", "Constitutional Ban", "Statutory Ban", "Legal"), labels = c("No Law", "Constitutional Ban", "Statutory Ban", "Legal"))

# tidying the appearance of Year for visualization
ssm_tidy$Year2 <- factor(ssm_tidy$Year, labels = c("'95", "'96", "'97", "'98", "'99", "'00", "'01", "'02", "'03", "'04", "'05", "'06", "'07", "'08", "'09", "'10", "'11", "'12", "'13", "'14", "'15"))

# facet grid
ggplot(data = ssm_tidy) +
  geom_bar(mapping = aes(x = Law, fill = Law)) +
  facet_grid(Law ~ Year2) +
      labs(title = "Change in Legal Status of Same-Sex Marriage in the US (1995-2015)",
       y = "number of states",
       caption = "(based on data from the Pew Research Center)") +
      theme(strip.background = element_blank(),
            axis.title.x = element_blank(),
            axis.text.x = element_blank(),
            axis.ticks.x = element_blank())
ggsave("facet_law_year.png")  

```



